services:
  db:
    image: "postgres:16-alpine"
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - network

  web:
    build:
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - network

  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379
    networks:
      - network
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:

networks:
  network:
    driver: bridge

