services:
  test_db:
    image: "postgres:16-alpine"
    working_dir: "/code"
    ports:
      - 5433:5433
    env_file:
      - .env
    networks:
      - network

networks:
  network:
    driver: bridge
